### ISSUE TITLE
Add OS selection to configurable options

### ISSUE THREAD

**Issue by astewartipg** [UpCloudLtd/upcloud-whmcs-module#11]
Is there a way to choose which OS a customer wants to use on their VPS?  It doesn't seem to be in the default configurable options.  Only size and location

**Comment by Xiloror** [comment]
I want this too, any update?

**Comment by andrisutanto** [comment]
Is there any update for this?

**Comment by rjsurjo** [comment]
Please add Choise OS Option on whmcs Module

**Comment by imiguelsalcedo** [comment]
I am not a programmer, but I added a couple of things to make it possible to choose the operating system from configurable options.

[https://github.com/imiguelsalcedo/upcloud-whmcs-module/commit/a043fa1344c1b8d8f563eb84d2e5d2cba826556c?branch=a043fa1344c1b8d8f563eb84d2e5d2cba826556c&diff=split](https://github.com/imiguelsalcedo/upcloud-whmcs-module/commit/a043fa1344c1b8d8f563eb84d2e5d2cba826556c?branch=a043fa1344c1b8d8f563eb84d2e5d2cba826556c&diff=split)

**Comment by isarpila** [comment]
We have just updated our module and therefor closing this issue as we considered it not being a problem anymore.

However if you thing otherwise please open a new github-issue.

**Comment by isarpila** [comment]
This is now possible due to recent update we did into module. Feel free to open a new issue in case you have notices something not working though.
