### ISSUE TITLE
VNC not working

### ISSUE THREAD

**Issue by astewartipg** [UpCloudLtd/upcloud-whmcs-module#12]
Ran through the VNC setup part of the install instructions, but when clicking on VNC in the client area, or Run VNC in the admin area of whmcs, it just gives a connection error

![upcloudvnc](https://user-images.githubusercontent.com/56042322/72646183-e5442400-394b-11ea-8ae6-1290cd8751fe.png)

**Comment by isarpila** [comment]
We have updated our module lately. Hope it works for you now. If not please open a new issue with as detailed description as possible. Thanks in advance!
