### ISSUE TITLE
Cannot clone 'hdd' storages from private templates.

### ISSUE THREAD

**Issue by devrhcrypto** [UpCloudLtd/upcloud-whmcs-module#13]
Cannot clone 'hdd' storages from private templates.

**Comment by arialfisyahrin** [comment]
in manage orders whmcs admin, show error 'Cannot clone 'hdd' storages from private templates.
'

**Comment by jomsky10** [comment]
please add the support for custom images on your whmcs module this is very important.

**Comment by isarpila** [comment]
This is now possible due to recent update we did into module. Feel free to open a new issue in case you have notices something not working though.
