### ISSUE TITLE
The request body contains an unknown attribute vnc

### ISSUE THREAD

**Issue by dlozev** [UpCloudLtd/upcloud-whmcs-module#2]
I get the following error when I tried to create a new VPS (after completing this installation tutorial):
The request body contains an unknown attribute vnc.

**Comment by akinolaking** [comment]
I am getting a similar error on a fresh WHMCS installation.

**Comment by exonhost** [comment]
I am also getting same error.

**Comment by jnicotra** [comment]
I am getting the same error as well. According to comments on their WHMCS guide, there is a known error with the new API.

**Comment by arialfisyahrin** [comment]
I am also getting same error. please give feedback

**Comment by neggs** [comment]
Ditto

**Comment by astewartipg** [comment]
I'm getting this as well.  When will a fix be release?

**Comment by jnicotra** [comment]
I've been following up with them ever couple of weeks. They mentioned they are testing the new release and that it is at the top of their priority list. Hopefully it'll come soon!

**Comment by aldhy** [comment]
I get same error

**Comment by wpexpertinbd** [comment]
Same here...

**Comment by Raiou** [comment]
This error should now be fixed. Just re-download and copy in the module to any existing WHMCS installation to give it a try.
