### ISSUE TITLE
Stuck at Module Settings when adding product

### ISSUE THREAD

**Issue by pao2pao16** [UpCloudLtd/upcloud-whmcs-module#21]
Hi,

My WHMCS is stuck at this loading screen when adding the module settings in add product page.

![module-setting](https://user-images.githubusercontent.com/47048813/84022542-0835aa00-a9b9-11ea-9c23-855f4c276c2f.png)

More info:

Inspect Elements > Network shows 500 Internal Server Error

Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

**Comment by Dexxa1024** [comment]
I'm having the same problem to, Anyone know how to fix it?

**Comment by pao2pao16** [comment]
This appears to be an abandoned project

**Comment by ethaniel86** [comment]
same issue here on WHMCS 8.0. module development no longer active?

**Comment by crossrims** [comment]
Same issue over here; WHMCS 8.0

**Comment by pao2pao16** [comment]
Hi All,

Fork by wiryonolau seems is working
https://github.com/wiryonolau/upcloud-whmcs-module

**Comment by isarpila** [comment]
This is now possible due to recent update we did into module. Feel free to open a new issue in case you have notices something not working though.
