### ISSUE TITLE
Backup/snapshot also firewall pricing input for WHMCS admin

### ISSUE THREAD

**Issue by adepondra** [UpCloudLtd/upcloud-whmcs-module#23]
Please add backup/snapshot also firewall pricing input for WHMCS admin, this module is working well but there is no place to set the backup and firewall price.

**Comment by thevilledev** [comment]
Hey, we are grouping similar issues into single feature requets. This continues in https://github.com/UpCloudLtd/upcloud-whmcs-module/issues/59. Thanks!
