### ISSUE TITLE
The client account has full control over the server!

### ISSUE THREAD

**Issue by kvmnodes** [UpCloudLtd/upcloud-whmcs-module#24]
Hello UpCloud!

I am testing the packages, currently have a problem that I cannot control. Features such as:
- Backups Management
- Network Management
- Firewall Management

When customers buy Cloud packages, and are immediately provided with features such as backup, adding IP4, turning on Firewall (although not paying for these addons) https://ibb.co/gRJZqZ8

I cannot disable these features from a client account.
And how to create addons by asking customers to pay. I tried creating a cloud, and when I left out the option to add addons, but the guest account can still use it.

Help me!

**Comment by imiguelsalcedo** [comment]
Hello, you can deactivate it with a hook.

`if(!is_null($primarySidebar->getChild('ManageVM'))){
             $primarySidebar->getChild('ManageVM')
                   ->removeChild('snapshotsManagement')
                   ->removeChild('networkManagement')
                   ->removeChild('firewallManagement');
 }`

In the case of network management, it may be important to leave it so that they can edit the rDNS but you can modify the view to remove the add new ip buttons.

**Comment by thevilledev** [comment]
Hey, we are grouping similar issues into single feature requests. This continues in https://github.com/UpCloudLtd/upcloud-whmcs-module/issues/59. Thanks!
