### ISSUE TITLE
OS Configurable Options

### ISSUE THREAD

**Issue by uswhss** [UpCloudLtd/upcloud-whmcs-module#25]
The problem is it's pretty much useless because there is no configurable option to allow the client to choose the OS when ordering. Honestly, what was the developer thinking? This is a very basic requirement for placing an order for any server right?

I know your dev is going to say just create a product for each OS. Well, let's think about that...

12 Locations x 10 server sizes x 11 OS options = 1,320 Products. I think you get the point that's not doable.

**Comment by imiguelsalcedo** [comment]
Hello, this can be done by code inspection. Look at **Location** and you will be able to do the operating system choice.

**Comment by isarpila** [comment]
This is now possible due to recent update we did into module. Feel free to open a new issue in case you have notices something not working though.

**Comment by astewartipg** [comment]
I just installed the latest version, and I do not see a spot where the customer can choose the location.  I see that it can only be configured in the package itself.  Can you please let me know how I can configure this so the CUSTOMER can choose which location they want to sign up on.

**Comment by isarpila** [comment]
Sorry closing this too early but we are just about to release an update where this is fixed.

**Comment by isarpila** [comment]
opening as not fixed yet

**Comment by thevilledev** [comment]
Hey, apologies. We are about to release a new version of the module. This time for real. Please open a new issue if this still persists.
