### ISSUE TITLE
Things that need to be in this module for it to be useful

### ISSUE THREAD

**Issue by astewartipg** [UpCloudLtd/upcloud-whmcs-module#27]
Unless I'm missing some configurations somewhere that I can tweak, this module is not useful to me as a reseller.

Here's what needs to be added.

1.  Allow Customers to choose a location.   Right now, it looks like the only way a customer can choose a location, is if I create a package for every server type, in every location.   When a customer chooses what package they want to order from me, there should be a drop down that displays all the locations they can choose from.
2.  Allow customers to choose a template (OS).   Same as above.  I can't create a package in the WHMCS for every single OS you guys support.  This is something that a customer signing up should be able to just choose from a dropdown, or similar.
3. Allow me to disable things like Backups, and add IP's.  If a customer Adds a backup, or an IP from their client area in the WHMCS, how am I supposed to bill them for it.  UpCloud will certianly bill me, but I don't have a way to automate it so I can bill my customer.

It seems like you guys are looking at this as if the owner of the account is the only person that will be using it.  If that was the case, what's even the point of having an UpCloud Plugin.  I can just do all of this from my account on the UpCloud website.  I need this to be usable by my own customers, and without having to monitor every client's account to see if they did anything that's going to cost me more money so I can charge my own customers.

**Comment by thevilledev** [comment]
Hey! Thanks for the feedback. It's been a while, but we are releasing a new version of the module soon. You can choose a location and a OS template.

As for pricing functionality in admin area for all available options from the client area, feel free to follow this task: https://github.com/UpCloudLtd/upcloud-whmcs-module/issues/59. Thanks!
