### ISSUE TITLE
Testing fails on non-upcloud servers

### ISSUE THREAD

**Issue by astewartipg** [UpCloudLtd/upcloud-whmcs-module#3]
I have setup the UpCloud module on 3 different WHMCS installs with 3 different servers.

1 is on an upcloud server
2 are with other datacenters.

The one on upcloud works fine

The other 2 both fail to test.  They don't actually give any errors, it just sits there saying testing connection.  It never times out, never gives an error.

I have enabled Allow API connections from All addresses on the user I'm using.  The same user works on the UC server, but does not work on the 2 non-UC server.

It seems as though the API may be blocking connections from servers not hosted at UC

**Comment by Raiou** [comment]
We've made an update to the module that should allow connection from other data centres.

**Comment by astewartipg** [comment]
This still does not appear to work.  WHen I click on test connection, the indicator just spins.  It never gives an error, and never actually connections.

**Comment by twicealive** [comment]
When I click on test connection, the indicator just spins. It never gives an error, and never actually connects.

Also, please provide a webhook file so whmcs can communicate with Stripe.

Thank you

**Comment by thevilledev** [comment]
Hey, we are about to release a new version of the module. Please open a new issue if this still persists.
