### ISSUE TITLE
Set distinctive HTTP `User-Agent` header

### ISSUE THREAD

**Issue by scop** [UpCloudLtd/upcloud-whmcs-module#33]
https://github.com/UpCloudLtd/upcloud-whmcs-module/blob/bde802af992426fdb2e132d38c77be91a94e9a0c/modules/servers/upCloudVps/lib/upCloudVps.php#L36-L38

We should set a distinctive HTTP `User-Agent` header for requests made by this module. Something like
```php
$this->setHttpHeader('User-Agent', 'upcloud-whmcs-module/X.Y.Z'); // Or upcloud-whmcs-server-module or something
```
...with `X.Y.Z` being the module version, coming from some variable that gets updated on all releases.

**Comment by scop** [comment]
Actually, likely better done using `CURLOPT_USERAGENT`.

**Comment by thevilledev** [comment]
Done in #54
