### ISSUE TITLE
Error provisioning Ubuntu 1804 image

### ISSUE THREAD

**Issue by jnnngs** [UpCloudLtd/upcloud-whmcs-module#4]
The following error appears after trying to provision a Ubuntu image (London)...

The request body contains an unknown attribute vnc

**Comment by Raiou** [comment]
This error should now be fixed.

**Comment by isarpila** [comment]
We have updated our module lately. Hope it works for you now. If not please open a new issue with as detailed description as possible. Thanks in advance!
