### ISSUE TITLE
Module is totally not working!

### ISSUE THREAD

**Issue by wpexpertinbd** [UpCloudLtd/upcloud-whmcs-module#6]
Hello, Not able to assign any existing vm or not able create any vm from admin, even any function not working from admin panel. whmcs 7.8.3 & your module latest one.

**Comment by Raiou** [comment]
We've made an update to fix an underlying issue which should solve most problems. Re-download the module for another try to see if it now works for you.

**Comment by wpexpertinbd** [comment]
Kindly check new issue here: https://github.com/UpCloudLtd/upcloud-whmcs-module/issues/7
