### ISSUE TITLE
Unable to parse response as JSON

### ISSUE THREAD

**Issue by wpexpertinbd** [UpCloudLtd/upcloud-whmcs-module#7]
Hello, now not able to add server. While I try to upcloud as a server & hit Test Connection from whmcs then i got this error: Unable to parse response as JSON

This is your latest version

**Comment by wpexpertinbd** [comment]
I solve this issue it was hostname issue at server creation page, now when I going to create product & try create configurable option then below error come
Exception: Unable to parse response as JSON in /home/example/public_html/modules/servers/upCloudVm/Manager.php:137
 & custom field created successfully .

Also, don't see any way to add existing server & if i manually insert hostname, ip, user id & password & active the order then it's showing "error no server found". Even no function working if i hit from admin panel. client are showing "Something went wrong. Please try again later."

**Comment by Raiou** [comment]
Entering the API URL is now required for the module to be able to connect. We've updated the [instructions on our tutorial](https://upcloud.com/community/tutorials/get-started-upcloud-whmcs-module/) to reflect the change.

**Comment by Raiou** [comment]
The problem of generating configurable options seems to be related to the change of how the API URL is handled. Should have this fixed shortly.

**Comment by Raiou** [comment]
This should now also be fixed.

**Comment by wpexpertinbd** [comment]
Thanks, may i download it now & try?

**Comment by Raiou** [comment]
Of course, and feel free to report any other issues you might face.
