### ISSUE TITLE
not adding new signups

### ISSUE THREAD

**Issue by astewartipg** [UpCloudLtd/upcloud-whmcs-module#9]
I installed the new version that was released today.  I added an order in my whmcs, and when I accepted the order, it accepted successfully, but it never actually added it to my account at upcloud.  The upcloud module does test successfully however.  It just doesn't seem to do anything else.

**Comment by Raiou** [comment]
[What did you select as the setup method](https://upcloud.com/wp-content/uploads/2019/04/whmcs-13-product-module-settings.png)? You have the option to automatically accept orders which will deploy a new cloud server by itself, the other options will require you to accept the order on the admin panel or manually create the server in the order details.

**Comment by astewartipg** [comment]
found the issue, was on my end
